### ISSUE TITLE
`docker save` sometimes returns images missing blobs

### ISSUE THREAD

**Issue by cowwoc** [ligfx/k3d-registry-dockerd#13]
Version 0.7

If I enable the following option in k3d's config file:

```
options:
  k3s:
    extraArgs:
      - arg: "--disable-default-registry-endpoint"
        nodeFilters:
          - "all:*"
```

Then coredns fails to load properly:

  Normal   Pulling    26s   kubelet            Pulling image "registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.5.1"
  Warning  Failed     5s    kubelet            Failed to pull image "registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.5.1": rpc error: code = NotFound desc = failed to pull and unpack image "registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.5.1": failed to copy: httpReadSeeker: failed open: could not fetch content descriptor sha256:8fd3d3275362698251cd271235e68f78674a216a940db7e4857cda5302c2ce5a (application/vnd.oci.image.config.v1+json) from remote: not found

All other images seem to work fine.

Removing the above option allows k3d to bypass your proxy if it runs into an error using it, which is probably why you're not seeing this error without it.

**Comment by ligfx** [comment]
Works for me with the config file:

```yaml
apiVersion: k3d.io/v1alpha5
kind: Simple
options:
  k3s:
    extraArgs:
    - arg: "--disable-default-registry-endpoint"
      nodeFilters:
      - "all:*"
registries:
  create:
    image: ligfx/k3d-registry-dockerd
    proxy:
      remoteURL: "*"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

And running `kubectl run mypod --image=registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.5.1` manually, since `kube-webhook-certgen` doesn't seem to be used in my install of k3d.

Can you provide more information?
