### ISSUE TITLE
Using the image during local development

### ISSUE THREAD

**Issue by yakom** [ligfx/k3d-registry-dockerd#15]
hello,

are there any examples on how to use this image with a k3d cluster and cached built locally?   both the readme and [this post](https://thoughtexpo.com/k3d-images/) i found suggest it should work out of the box, but it doesn't for me.

my steps:
1. i create a k3d registry using this image as the custom one.
2. i create a k3d cluster. both these steps involve the proxying configuration.
3. i build an application image locally and tag it with the registry's domain (`k3d-registry.localhost:5000` in my case).
4. i apply a deployment using the image to the k3d cluster, but the image cannot be pulled.   it doesn't matter if i use the registry domain or not in the image spec, neither works.
5. an observation - it seems the previous version of that image, one that existed in my local Docker image cache was visible to the registry which was created later, and got cached by it somewhere.   however, no image built after the registry got created is usable from the cluster.

i don't know if it's a bug, or whether i'm doing something wrong?   i can provide details if needed?

**Comment by ligfx** [comment]
Hi @yakom 👋 You should be able to tag images without a registry name and then use them normally (or maybe with a `docker.io/` registry name?). Let me know if that works.

**Comment by yakom** [comment]
> Hi [@yakom](https://github.com/yakom) 👋 You should be able to tag images without a registry name and then use them normally (or maybe with a `docker.io/` registry name?). Let me know if that works.

hello, it doesn't, unfortunately.   to list my steps:

`k3d registry create --port 5000 --image ligfx/k3d-registry-dockerd:v0.7 --volume ${HOME}/srv/docker-registry:/var/lib/registry --volume /var/run/docker.sock:/var/run/docker.sock docker-registry.localhost`

`K3D_FIX_DNS=0 k3d cluster create mars-cluster --agents 2 --port "127.0.0.1:8081:80@loadbalancer" --registry-use k3d-docker-registry.localhost:5000 --registry-config ${HOME}/srv/docker-registry.yml --volume ${HOME}/srv/mars-volumes:/var/lib/rancher/k3s/storage@all`

where `docker-registry.yml` holds:
```
mirrors:
  "*":
    endpoint:
      - http://k3d-docker-registry.localhost:5000
```

the cluster on works fine on its own. but once i build my image and run

`docker tag mars-backend:latest k3d-docker-registry.localhost:5000/mars-backend:latest`

i try to deploy:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mars-backend-deployment
  labels:
    application: mars-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      application: mars-backend
  template:
    metadata:
      labels:
        application: mars-backend
    spec:
      containers:
      - name: mars-backend
        image: k3d-docker-registry.localhost:5000/mars-backend:latest
        ports:
        - containerPort: 8080
     ...
```

and the image cannot be pulled.   it doesn't matter if i put `docker.io` as the registry, or omit the registry altogether.

have you got an idea of what am i doing wrong?
